In [3]:
import numpy as np
import time
import matplotlib.pyplot as plt
!pip install scienceplots
import scienceplots as sp
import sys
plt.style.use(['science','notebook','grid'])



In [85]:
x = np.array([1,2])
print(f" the given input is of type {type(x)} has an shape {x.shape} and looks like {x}")

 the given input is of type <class 'numpy.ndarray'> has an shape (2,) and looks like [1 2]


In [86]:
w = np.array([[1,-2],[2,1],[1,-1]])
w = w.T
print(f" the given input is of type {type(w)} has an shape {w.shape} and looks like {w}")
b = np.array([5,2,6])
print(f" the given input is of type {type(b)} has an shape {b.shape} and looks like {b}")

 the given input is of type <class 'numpy.ndarray'> has an shape (2, 3) and looks like [[ 1  2  1]
 [-2  1 -1]]
 the given input is of type <class 'numpy.ndarray'> has an shape (3,) and looks like [5 2 6]


In [87]:
def sigmoid(x):
  zo = 1/(1+np.exp(-x))
  return zo

In [103]:
def dense(x_in , w , b):
  number_of_neurons = w.shape[1]
  activation_array = np.zeros(number_of_neurons)
  for i in range (number_of_neurons):
    z_i = np.dot(w[:,i],x_in)+b[i]
    activation_array[i] = sigmoid(z_i)

  return activation_array

In [104]:
a1 = dense(x,w,b)
print(f" layer 1 activation ==>{a1}")

 layer 1 activation ==>[0.88079708 0.99752738 0.99330715]


In [105]:

w1 = np.array([[1,-1,-1]])
w1 = w1.T
b1 = np.array([4])
def sequential(lol):
  a1_ = dense(lol,w,b)
  a2_ = dense(a1,w1,b1)
  return a2_

print(sequential(x))

[0.94734801]


In [106]:
x_2d = np.array([[1,2]])
w_2d = np.array([[1,-2],[2,1],[1,-1]])
w_2d = w_2d.T
b_2d = np.array([[5,2,6]])
print(w_2d)

[[ 1  2  1]
 [-2  1 -1]]


In [107]:
def dense_vectorized(x_in ,w,b):
  z = np.matmul(x_in,w)
  z = z+b
  activation_array = sigmoid(z)
  return activation_array


In [108]:
a1_vec = dense_vectorized(x,w_2d,b_2d)
print(a1_vec)

[[0.88079708 0.99752738 0.99330715]]


In [109]:
w1_vec = np.array([[1,-1,-1]])
w1_vec = w1_vec.T
b1_vec = np.array([[4]])
def sequential(lol):
  a1_ = dense_vectorized(lol,w,b)
  a2_ = dense_vectorized(a1,w1_vec,b1_vec)
  return a2_

print(sequential(x))

[[0.94734801]]
